# Generated by Django 5.2.4 on 2025-07-19 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.CharField(max_length=150)),
                ('medico', models.CharField(max_length=150)),
                ('data_hora', models.DateTimeField()),
                ('motivo', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('AG', 'Agendada'), ('CN', 'Cancelada'), ('RF', 'Reagendada'), ('FN', 'Finalizada')], default='AG', max_length=2)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
